version: "3.8"
services:
  api:
    build: .
    image: api:1.0
    ports:
      - "8000:8000"
    networks:
      - red-api-db
    depends_on:
      - mysqldb
  
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dmr2003
      - MYSQL_DATABASE=prueba
    volumes:
      - mysql-persistencia:/var/lib/mysql
    networks:
      - red-api-db

volumes:
  mysql-persistencia:

networks:
  red-api-db: 

